### PR TITLE
Added playerid chip

### PR DESCRIPTION
**Pull request by Mordenkainen**
Added playerid, which is a copy of the vehicleid chip, but returns playerid.

### CODE REVIEW

**Comment by nightkr** [comment]
When trying to use the playerid chip (04ab940 test build) I just get an error about that I should point at the circuit sign.

**Comment by Mordenkainen** [comment]
At what point do you get this error? On activation? How are you activating the chip?

**Comment by nightkr** [comment]
Yes, on activation. I activate using `/rcactivate` while pointing at the sign as I usually do, since there are problems with the mine way to do it (creative mode doesn't mix well up with RC ATM).

**Comment by Mordenkainen** [comment]
HMMM. Strange. The rcactivate command knows nothing about the chip it is activating. If it works for one, it should work for all. Does the issue only happen in creative? Also, if I am understanding you right, clicking on the sign doesn't work in creative? What other issues have you seen?

**Comment by nightkr** [comment]
I have tried temporarily disabling creative too, with the same issue.
Also, the issue when using redstonechips click-activation in creative is that just after activating it it destroys the sign. Which deactivates it.

**Pull request merged**
